image: "ruby:2.6"

cache:
  paths:
    - node_modules/
    - .yarn

services:
  - postgres:11

before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - yarn install --check-files

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop
